### ISSUE TITLE
Any recommendations specifically designed for nginx?

### ISSUE THREAD

**Issue by GwynethLlewelyn** [nsacyber/Mitigating-Web-Shells#6]
Hello,

I've noticed that you have included several detailed instructions for Microsoft IIS as well as Apache. I wonder if you could also make some recommendations for `nginx` — it's [an increasingly popular web server](https://w3techs.com/technologies/overview/web_server), with almost as much market share as Apache. While web server log analysis can be used with relative facility (`nginx` can write its logs in Apache format), other tools mentioned on your documentation do not apply.

Thanks in advance!

**Comment by CyberRookie** [comment]
I have not tried that service. Is it a container or a full-fledged server?
________________________________

**Comment by GwynethLlewelyn** [comment]
It's a full-fledged server, created in 2004. It can also be used as a reverse proxy, load balancer, mail proxy and HTTP cache. While the server itself is free and open-source (used, for instance, by Cloudflare... among a zillion other websites), there is a company behind it (Nginx, Inc.) which _also_ develops something akin to 'containers', which they call 'a polyglot app server' (named '[Unit](https://unit.nginx.org/)'). Nginx is also, according to Wikipedia, the most deployed web server on Docker containers (because it's small in size, needs few resources, and is blazingly fast).

I'm actually surprised that you haven't heard about `nginx` before lol — after all, it is used by 4x as many websites as IIS, and, as said, almost as many as Apache...

**Comment by CyberRookie** [comment]
Maybe I'll check it out. I allready run Apache Tomcat and J-Boxss EAP server for MySQL and Persistence/Hibernate.
________________________________

**Comment by GwynethLlewelyn** [comment]
While you can most certainly run [Apache Tomcat behind `nginx`](https://www.atlantic.net/vps-hosting/how-to-setup-tomcat-with-nginx-as-a-reverse-proxy-on-ubuntu-18-04/) (the configuration on that page is a bit simplistic and not for Red Hat, but Ubuntu/Debian; to get the full advantages of `nginx`, it requires a bit more of tweaking — namely, to properly cache requests and work as a low-mem, low-CPU, high-performance reverse proxy, even serving static content such as images and CSS/JS files directly from the disk, bypassing Tomcat completely...), I could not read much about **J-Boxss EAP**, which is a commercial product, and it's possible that it runs 'behind' Apache... so I guess that you wouldn't profit a lot from `nginx` in that scenario.

**Comment by iadgovuser41** [comment]
Hi GwynethLlewelyn, 
We currently don't have additional instructions for nginx but we'll consider adding this in a future revision. In the mean time, if there are any specific nginx instructions that you believe would be valuable, please submit them and we'll review for possible inclusion in the guidance.
