### ISSUE TITLE
Use the correct licenses

### ISSUE THREAD

**Issue by jvoisin** [nsacyber/Mitigating-Web-Shells#7]
Your [current license]( https://github.com/nsacyber/Mitigating-Web-Shells/blob/master/LICENSE.md ) is bullshit, and I would appreciate that you don't steal [my code]( https://github.com/nsacyber/Mitigating-Web-Shells/blob/master/core.webshell_detection.yara#L56-L66 ) if you can't abide by its license.

**Comment by iadgovuser41** [comment]
The referenced code was removed
