### ISSUE TITLE
Replace my nickname with proper .htaccess webshell detection?

### ISSUE THREAD

**Issue by EMSeek** [nsacyber/Mitigating-Web-Shells#8]
See https://github.com/nbs-system/php-malware-finder/issues/3

**Comment by iadgovuser41** [comment]
Feel free to suggest a .htaccess webshell detection rule. We will review the rule and merge with the existing codebase if the detection rate is acceptable.

**Comment by wireghoul** [comment]
Pull request submitted: #9
